"""
Environment generator service.
Handles single environment package generation and batch generation with perturbations.
"""
import io
import json
import logging
import random
import uuid
import zipfile
import copy
from datetime import datetime
from typing import Optional

from sqlalchemy.ext.asyncio import AsyncSession

from app.config import settings
from app.models.env import Env
from app.schemas.env_config import EnvConfig

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Python templates for generated environment code
# ---------------------------------------------------------------------------
CORE_PY_TEMPLATE = '''"""
FlightEnv - Gymnasium Environment for Flight Testing
Auto-generated by FLTECT environment generator.
"""
import json
import numpy as np
import gymnasium as gym
from gymnasium import spaces


class FlightEnv(gym.Env):
    """Custom Flight Test Environment wrapping JSBSim."""

    metadata = {{"render_modes": ["human"], "name": "FlightTestEnv-v0"}}

    def __init__(self, config_path: str = "config.json", render_mode=None):
        super().__init__()
        with open(config_path, "r") as f:
            self.config = json.load(f)

        self.terrain = self.config.get("terrain", {{}})
        self.weather = self.config.get("weather", {{}})
        self.flight_dynamics = self.config.get("flight_dynamics", {{}})
        self.rewards = self.config.get("rewards", {{}})
        self.obstacles = self.config.get("obstacles", {{}})
        self.waypoints = self.config.get("waypoints", [])

        self.action_space = spaces.Box(
            low=np.array([-1.0, -1.0, -1.0, -1.0]),
            high=np.array([1.0, 1.0, 1.0, 1.0]),
            dtype=np.float32,
        )

        self.observation_space = spaces.Box(
            low=np.array([-180.0, -90.0, 0.0, -100.0, -100.0, -100.0]),
            high=np.array([180.0, 90.0, 50000.0, 100.0, 100.0, 100.0]),
            dtype=np.float32,
        )

        self.current_step = 0
        self.max_steps = 1000
        self.state = np.zeros(6, dtype=np.float32)
        self.render_mode = render_mode

    def reset(self, seed=None, options=None):
        super().reset(seed=seed)
        self.current_step = 0
        self.state = np.zeros(6, dtype=np.float32)
        self.state[2] = 100.0
        obs = self.state.copy()
        info = {{"episode_reward": 0.0, "success_rate": 0.0}}
        return obs, info

    def step(self, action):
        action = np.clip(action, -1.0, 1.0)
        self.state[0] += action[0] * 0.1
        self.state[1] += action[1] * 0.1
        self.state[2] += action[2] * 10.0
        self.state[3] = action[0] * 50.0
        self.state[4] = action[1] * 50.0
        self.state[5] = action[2] * 50.0

        self.state = np.clip(self.state, self.observation_space.low, self.observation_space.high)
        reward = self._compute_reward()
        self.current_step += 1
        terminated = self.current_step >= self.max_steps
        truncated = self.state[2] <= 0.0
        info = {{
            "altitude": float(self.state[2]),
            "velocity": float(np.linalg.norm(self.state[3:6])),
        }}
        return self.state.copy(), reward, terminated, truncated, info

    def _compute_reward(self):
        reward = 0.0
        for item in self.rewards.get("reward_items", []):
            reward += item.get("coefficient", 1.0)
        for item in self.rewards.get("penalty_items", []):
            reward -= item.get("coefficient", 1.0)
        return reward

    def render(self):
        if self.render_mode == "human":
            print(f"Step: {{self.current_step}}, State: {{self.state}}")

    def close(self):
        pass
'''

REWARD_PY_TEMPLATE = '''"""Reward computation for FlightEnv."""
import numpy as np


def compute_reward(state, action, config, waypoints=None):
    """Compute the reward for a given state-action pair."""
    reward = 0.0
    reward_items = config.get("rewards", {{}}).get("reward_items", [])
    penalty_items = config.get("rewards", {{}}).get("penalty_items", [])

    for item in reward_items:
        reward += item.get("coefficient", 1.0)

    for item in penalty_items:
        reward -= item.get("coefficient", 1.0)

    if state[2] < 0:
        reward -= 100.0

    if waypoints:
        closest_dist = float("inf")
        for wp in waypoints:
            pos = wp.get("position", [0, 0, 0])
            dist = np.linalg.norm(np.array(state[:3]) - np.array(pos))
            closest_dist = min(closest_dist, dist)
        reward -= closest_dist * 0.01

    return float(reward)
'''


# ---------------------------------------------------------------------------
# Single environment package generation
# ---------------------------------------------------------------------------
async def generate_env_package(
    env: Env,
    config: EnvConfig,
    db: AsyncSession,
) -> str:
    """Generate a downloadable environment package and upload to MinIO."""
    try:
        from minio import Minio
        from app.config import settings

        minio_client = Minio(
            settings.MINIO_ENDPOINT,
            access_key=settings.MINIO_ACCESS_KEY,
            secret_key=settings.MINIO_SECRET_KEY,
            secure=settings.MINIO_SECURE,
        )
    except Exception as e:
        logger.error(f"Failed to initialize MinIO client: {e}")
        raise

    if not minio_client.bucket_exists(settings.BUCKET_NAME):
        minio_client.make_bucket(settings.BUCKET_NAME)

    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, "w", zipfile.ZIP_DEFLATED) as zf:
        config_dict = config.model_dump()
        zf.writestr("config.json", json.dumps(config_dict, indent=2))

        zf.writestr("core.py", CORE_PY_TEMPLATE)
        zf.writestr("reward.py", REWARD_PY_TEMPLATE)

        scene_json = json.dumps({
            "terrain": config_dict.get("terrain", {}),
            "weather": config_dict.get("weather", {}),
            "obstacles": config_dict.get("obstacles", {}),
            "waypoints": config_dict.get("waypoints", []),
            "runway": {
                "length": 2000,
                "width": 30,
                "heading": 0,
                "position": [0, 0, 0],
            },
        }, indent=2)
        zf.writestr("scene.json", scene_json)

        jsbsim_xmls = _generate_jsbsim_xmls(config)
        for name, content in jsbsim_xmls.items():
            zf.writestr(f"jsbsim/{name}", content)

    buffer.seek(0)
    object_name = f"envs/{env.id}/package.zip"
    minio_client.put_object(
        settings.BUCKET_NAME,
        object_name,
        buffer,
        length=buffer.getbuffer().nbytes,
        content_type="application/zip",
    )

    storage_path = f"s3://{settings.BUCKET_NAME}/{object_name}"
    env.storage_path = storage_path
    env.status = "ready"
    await db.commit()

    logger.info(f"Environment package generated for env {env.id}: {storage_path}")
    return storage_path


def _generate_jsbsim_xmls(config: EnvConfig) -> dict[str, str]:
    terrain = config.terrain
    weather = config.weather
    fd = config.flight_dynamics

    ground_xml = f"""<?xml version="1.0" encoding="UTF-8"?>
<ground>
  <terrain type="{terrain.type}">
    <elevation-min>{terrain.elevation_min}</elevation-min>
    <elevation-max>{terrain.elevation_max}</elevation-max>
    <resolution>{terrain.resolution}</resolution>
  </terrain>
</ground>"""

    weather_xml = f"""<?xml version="1.0" encoding="UTF-8"?>
<weather>
  <wind>
    <wind-speed>{weather.wind_speed}</wind-speed>
    <wind-direction-deg>{weather.wind_direction}</wind-direction-deg>
  </wind>
  <visibility>{weather.visibility}</visibility>
</weather>"""

    aircraft_xml = f"""<?xml version="1.0" encoding="UTF-8"?>
<aircraft name="{fd.aircraft_model}">
  <mass>{fd.mass}</mass>
  <wingspan>{fd.wingspan}</wingspan>
</aircraft>"""

    return {
        "ground.xml": ground_xml,
        "weather.xml": weather_xml,
        "aircraft.xml": aircraft_xml,
    }


# ---------------------------------------------------------------------------
# Batch environment generation
# ---------------------------------------------------------------------------
# Parameters that can be perturbed and their reasonable ranges
PERTURBATION_SPECS = {
    "wind_speed": {"min": 0, "max": 40, "type": "float"},
    "wind_direction": {"min": 0, "max": 360, "type": "float"},
    "visibility": {"min": 500, "max": 20000, "type": "float"},
    "elevation_min": {"min": 0, "max": 2000, "type": "float"},
    "elevation_max": {"min": 500, "max": 5000, "type": "float"},
    "obstacle_count": {"min": 0, "max": 50, "type": "int"},
    "obstacle_density": {"min": 0.0, "max": 1.0, "type": "float"},
    "mass": {"min": 500, "max": 50000, "type": "float"},
    "wingspan": {"min": 5, "max": 80, "type": "float"},
}


def _apply_perturbation(base_config: dict, param_name: str, delta: float) -> dict:
    """
    Apply a single perturbation to a config parameter.
    
    Args:
        base_config: The base configuration dict (will be deep-copied)
        param_name: Dot-notation path like "weather.wind_speed"
        delta: Amount to perturb (positive = increase, negative = decrease)
    
    Returns:
        New config dict with perturbation applied
    """
    config = copy.deepcopy(base_config)
    parts = param_name.split(".")
    
    target = config
    for part in parts[:-1]:
        if part in target and isinstance(target[part], dict):
            target = target[part]
        else:
            # Path doesn't exist, skip
            return config
    
    leaf_key = parts[-1]
    if leaf_key not in target:
        return config
    
    current_val = target[leaf_key]
    spec = PERTURBATION_SPECS.get(param_name, {})
    param_min = spec.get("min", float("-inf"))
    param_max = spec.get("max", float("inf"))
    param_type = spec.get("type", "float")
    
    try:
        new_val = float(current_val) + delta
        new_val = max(param_min, min(param_max, new_val))
        if param_type == "int":
            new_val = int(round(new_val))
        else:
            new_val = round(new_val, 4)
        target[leaf_key] = new_val
    except (ValueError, TypeError):
        logger.warning(f"Cannot perturb {param_name}: non-numeric value {current_val}")
    
    return config


def _generate_batch_configs(
    base_config: dict,
    count: int,
    deltas: Optional[list[dict]] = None,
) -> list[dict]:
    """
    Generate multiple configs by applying perturbations to a base config.
    
    Args:
        base_config: The starting configuration
        count: Number of configs to generate
        deltas: Optional list of {"param": "path", "delta": value} dicts.
                If None, random perturbations are generated.
    
    Returns:
        List of config dicts
    """
    configs = []
    
    if deltas is not None and len(deltas) > 0:
        # Use provided deltas with some randomization
        for i in range(count):
            config = copy.deepcopy(base_config)
            for delta_spec in deltas:
                param = delta_spec.get("param", "")
                delta_val = delta_spec.get("delta", 0)
                # Add some randomness to the delta
                noise = random.uniform(-abs(delta_val) * 0.2, abs(delta_val) * 0.2)
                config = _apply_perturbation(config, param, delta_val + noise)
            configs.append(config)
    else:
        # Generate fully random perturbations
        available_params = list(PERTURBATION_SPECS.keys())
        for i in range(count):
            config = copy.deepcopy(base_config)
            # Apply 2-4 random perturbations per config
            num_perturbations = random.randint(2, min(4, len(available_params)))
            chosen_params = random.sample(available_params, num_perturbations)
            
            for param_name in chosen_params:
                spec = PERTURBATION_SPECS[param_name]
                param_range = spec["max"] - spec["min"]
                # Perturb by up to 30% of the parameter range
                delta = random.uniform(-param_range * 0.3, param_range * 0.3)
                config = _apply_perturbation(config, param_name, delta)
            
            configs.append(config)
    
    return configs


async def batch_generate_envs(
    base_config: dict,
    count: int,
    deltas: Optional[list[dict]] = None,
    project_id: Optional[str] = None,
    creator_id: Optional[str] = None,
    db: AsyncSession = None,
    name_prefix: str = "Batch Env",
) -> list[str]:
    """
    Batch-generate multiple environments with perturbations.
    
    Args:
        base_config: Base configuration to perturb
        count: Number of environments to generate
        deltas: Optional explicit perturbation specs
        project_id: Project to assign envs to
        creator_id: User who created the batch
        db: Database session
        name_prefix: Prefix for environment names
    
    Returns:
        List of created environment IDs
    """
    if db is None:
        raise ValueError("Database session is required")
    
    configs = _generate_batch_configs(base_config, count, deltas)
    env_ids = []
    
    for i, config in enumerate(configs):
        env = Env(
            id=str(uuid.uuid4()),
            project_id=project_id,
            name=f"{name_prefix} #{i + 1}",
            config=config,
            status="draft",
            created_by=creator_id,
        )
        db.add(env)
        env_ids.append(env.id)
    
    await db.commit()
    
    logger.info(
        f"Batch generated {len(env_ids)} environments for project {project_id}"
    )
    
    return env_ids
